import type { ServiceSeed } from "./services-seed";

/** Generated by scripts/sync-oss-fund.mjs from oss-fund/directory (CC BY 4.0). Do not hand-edit. */
export const ossFundSeedMeta = {
  "syncedAt": "2026-08-25T08:42:34.053Z",
  "sourceCommit": "e0fca80421eff26c551db63ee12f94dd753dccbc",
  "source": "https://github.com/oss-fund/directory",
  "license": "CC-BY-4.0",
  "count": 31,
  "contentHashes": {
    "ossfund-algora": "78cdd770a94c5210",
    "ossfund-aws-promotional-credit": "b3cb295146393383",
    "ossfund-bepro-network": "97243ee1d3c3d466",
    "ossfund-bountyhub": "97c994096eb6d8aa",
    "ossfund-codeheat": "639ac5058c68b818",
    "ossfund-community-bridge": "658c3ad02d7ff960",
    "ossfund-eventyay": "277e00d62d9b65d1",
    "ossfund-faiross": "d202a3299c03da06",
    "ossfund-fund-request": "7d7e79c9ef63089e",
    "ossfund-git-pay": "c9f787e57a70b839",
    "ossfund-gitcoin": "8c2d41c3cf247270",
    "ossfund-github-sponsors": "f33c41c8004eee5d",
    "ossfund-goteo": "09429c27919f01d7",
    "ossfund-houdini": "c45117c2c37f91d1",
    "ossfund-issue-hunt": "2ecf2ffd95b9ee2a",
    "ossfund-liberapay": "4fed8f1185ac4539",
    "ossfund-libreselery": "2066edf861ee1ce5",
    "ossfund-nl-net": "613ec2e21eefaf21",
    "ossfund-numfocus": "aa40cedd5e03fdca",
    "ossfund-open-collective": "a5b3f4e0c50f4cca",
    "ossfund-open-source-design": "7185744635a310db",
    "ossfund-openssf": "1e36fceca4012222",
    "ossfund-opire": "97e416c794d9c647",
    "ossfund-osuosl": "576d3f8f2097d25d",
    "ossfund-season-of-docs": "31336d29b1685548",
    "ossfund-sf-conservancy": "12df49cb08f27f5b",
    "ossfund-sovereign-tech-fund": "90b606c35ef4662c",
    "ossfund-spi": "ed92731a1d5782ba",
    "ossfund-summer-of-code": "f48b03d3b56e329b",
    "ossfund-thanks": "0327e946656fc545",
    "ossfund-tidelift": "b2c626659a4201ef"
  }
} as const;

export const ossFundSeed: ServiceSeed[] = [
  {
    "id": "ossfund-algora",
    "slug": "algora",
    "name": "Algora",
    "category": "open_source",
    "offerType": "grant_credit",
    "resourceKind": "vendor_plan",
    "summary": "Algora is a developer tool & community simplifying bounties, hiring & open source sustainability. Imported from OSS.Fund on 2026-08-15 under CC BY 4.0.",
    "details": "Algora helps projects reward their contributors on Github using tips & bounties\n\nFees (OSS.Fund): 19% platform fee + 4% Stripe processing fee, paid by organizations on top of bounty payouts\n\nImported from OSS.Fund on 2026-08-15 under CC BY 4.0. Canonical listing: https://www.oss.fund/algora/",
    "absolutelyFree": false,
    "intermediaryRequired": false,
    "verification": [
      "none"
    ],
    "directPortalUrl": "https://algora.io/",
    "metaResource": false,
    "tags": [
      "oss.fund",
      "oss-project",
      "bounties",
      "developer-friendly",
      "open-source-friendly"
    ],
    "iconHint": "algora",
    "lastVerifiedAt": "2024-02-11",
    "stalenessStatus": "active",
    "listingKind": "standalone",
    "firstImportedAt": "2026-08-15",
    "lastUpdatedAt": "2026-08-25",
    "compare": {
      "freeCore": false,
      "intermediary": false,
      "verification": "Open source project / maintainer (see platform terms)",
      "notes": "Source: OSS.Fund. 19% platform fee + 4% Stripe processing fee, paid by organizations on top of bounty payouts"
    }
  },
  {
    "id": "ossfund-aws-promotional-credit",
    "slug": "aws-promotional-credit",
    "name": "AWS Promotional Credit",
    "category": "cloud_hosting",
    "offerType": "grant_credit",
    "resourceKind": "vendor_plan",
    "summary": "AWS credits to open source projects used to perform testing, CI/CD, or storage of artifacts on AWS. Imported from OSS.Fund on 2026-08-15 under CC BY 4.0.",
    "details": "AWS promotional credits to open source projects used to perform testing, CI/CD, or storage of artifacts on AWS.\tCorporation\tFree resources to further expand and innovate.\n\nFees (OSS.Fund): 0\n\nImported from OSS.Fund on 2026-08-15 under CC BY 4.0. Canonical listing: https://www.oss.fund/aws-promotional-credit/",
    "absolutelyFree": true,
    "intermediaryRequired": false,
    "verification": [
      "none"
    ],
    "directPortalUrl": "https://aws.amazon.com/blogs/opensource/aws-promotional-credits-open-source-projects/",
    "metaResource": false,
    "tags": [
      "oss.fund",
      "oss-project",
      "infrastructure",
      "open-source-friendly"
    ],
    "iconHint": "aws-promotional-credit",
    "lastVerifiedAt": "2020-06-20",
    "stalenessStatus": "active",
    "listingKind": "standalone",
    "firstImportedAt": "2026-08-15",
    "lastUpdatedAt": "2026-08-25",
    "compare": {
      "freeCore": true,
      "intermediary": false,
      "verification": "Open source project / maintainer (see platform terms)",
      "notes": "Source: OSS.Fund. 0"
    }
  },
  {
    "id": "ossfund-bepro-network",
    "slug": "bepro-network",
    "name": "BEPRO Network",
    "category": "open_source",
    "offerType": "grant_credit",
    "resourceKind": "vendor_plan",
    "summary": "Bepro is a task-based marketplace created to help organizations and builders thrive. Imported from OSS.Fund on 2026-08-15 under CC BY 4.0.",
    "details": "With BEPRO-Network, organizations can easily create and launch tasks, while builders have the opportunity to work on them and earn crypto as payment, providing a more efficient and transparent collaboration.\n\nFees (OSS.Fund): 10% fee to the marketplace\n\nImported from OSS.Fund on 2026-08-15 under CC BY 4.0. Canonical listing: https://www.oss.fund/bepro-network/",
    "absolutelyFree": false,
    "intermediaryRequired": false,
    "verification": [
      "none"
    ],
    "directPortalUrl": "https://app.bepro.network/",
    "metaResource": false,
    "tags": [
      "oss.fund",
      "oss-project",
      "bounties",
      "developer-friendly",
      "open-source-friendly",
      "marketplace"
    ],
    "iconHint": "bepro-network",
    "lastVerifiedAt": "2024-05-22",
    "stalenessStatus": "active",
    "listingKind": "standalone",
    "firstImportedAt": "2026-08-15",
    "lastUpdatedAt": "2026-08-25",
    "compare": {
      "freeCore": false,
      "intermediary": false,
      "verification": "Open source project / maintainer (see platform terms)",
      "notes": "Source: OSS.Fund. 10% fee to the marketplace"
    }
  },
  {
    "id": "ossfund-bountyhub",
    "slug": "bountyhub",
    "name": "BountyHub",
    "category": "open_source",
    "offerType": "grant_credit",
    "resourceKind": "vendor_plan",
    "summary": "BountyHub is a platform where developers can put bounties on their Github issues or earn money by solving them. Imported from OSS.Fund on 2026-08-15 under CC BY 4.0.",
    "details": "BountyHub, helps open-source maintainers monetize their repositories by allowing people or companies who use their repositories to place bounties on issues. Then contributors can earn money by solving the issues on their repositories.\n\nFees (OSS.Fund): 10% platform fee + payment processing fees, paid by bounty creators on top of bounty amount\n\nImported from OSS.Fund on 2026-08-15 under CC BY 4.0. Canonical listing: https://www.oss.fund/bountyhub/",
    "absolutelyFree": false,
    "intermediaryRequired": false,
    "verification": [
      "none"
    ],
    "directPortalUrl": "https://bountyhub.dev/",
    "metaResource": false,
    "tags": [
      "oss.fund",
      "oss-project",
      "bounties",
      "crowdfunding",
      "developer-friendly",
      "open-source-friendly",
      "marketplace"
    ],
    "iconHint": "bountyhub",
    "lastVerifiedAt": "2024-09-18",
    "stalenessStatus": "active",
    "listingKind": "standalone",
    "firstImportedAt": "2026-08-15",
    "lastUpdatedAt": "2026-08-25",
    "compare": {
      "freeCore": false,
      "intermediary": false,
      "verification": "Open source project / maintainer (see platform terms)",
      "notes": "Source: OSS.Fund. 10% platform fee + payment processing fees, paid by bounty creators on top of bounty amount"
    }
  },
  {
    "id": "ossfund-codeheat",
    "slug": "codeheat",
    "name": "Codeheat",
    "category": "open_source",
    "offerType": "grant_credit",
    "resourceKind": "vendor_plan",
    "summary": "Codeheat is a coding contest by FOSSASIA and OpnTec where students and professionals contribute to Open Source software and Open Hardware projects. Imported from OSS.Fund on 2026-08-15 under CC BY 4.0.",
    "details": "Codeheat is a coding contest by FOSSASIA and OpnTec where students and professionals contribute to Open Source software and Open Hardware projects. Winners are announced bi-monthly.\n\nFees (OSS.Fund): Based on choice of transfer\n\nImported from OSS.Fund on 2026-08-15 under CC BY 4.0. Canonical listing: https://www.oss.fund/codeheat/",
    "absolutelyFree": false,
    "intermediaryRequired": false,
    "verification": [
      "none"
    ],
    "directPortalUrl": "https://codeheat.org",
    "metaResource": false,
    "tags": [
      "oss.fund",
      "oss-project",
      "events",
      "open-source-friendly",
      "developer-friendly",
      "open-hardware",
      "students"
    ],
    "iconHint": "codeheat",
    "lastVerifiedAt": "2021-01-18",
    "stalenessStatus": "active",
    "listingKind": "standalone",
    "firstImportedAt": "2026-08-15",
    "lastUpdatedAt": "2026-08-25",
    "compare": {
      "freeCore": false,
      "intermediary": false,
      "verification": "Open source project / maintainer (see platform terms)",
      "notes": "Source: OSS.Fund. Based on choice of transfer"
    }
  },
  {
    "id": "ossfund-community-bridge",
    "slug": "community-bridge",
    "name": "Community Bridge",
    "category": "open_source",
    "offerType": "grant_credit",
    "resourceKind": "vendor_plan",
    "summary": "A Linux Foundation project to help advance sustainability, security, and diversity in open source technology by enabling developers to raise and spend funding. Imported from OSS.Fund on 2026-08-15 under CC BY 4.0.",
    "details": "A platform by Linux Foundation to help advance sustainability, security, and diversity in open source technology by enabling developers to transparently raise and spend funding; providing transparency into potential vulnerabilities and fixes; and advancing diversity.\n\nFees (OSS.Fund): Zero fees for first $10M donated through CommunityBridge. After that, 5% platform fee plus the payment processor’s fee.\n\nImported from OSS.Fund on 2026-08-15 under CC BY 4.0. Canonical listing: https://www.oss.fund/community-bridge/",
    "absolutelyFree": false,
    "intermediaryRequired": false,
    "verification": [
      "none"
    ],
    "directPortalUrl": "https://communitybridge.org/",
    "metaResource": false,
    "tags": [
      "oss.fund",
      "oss-project",
      "crowdfunding",
      "non-profit",
      "open-source-friendly",
      "developer-friendly",
      "security"
    ],
    "iconHint": "community-bridge",
    "lastVerifiedAt": "2020-06-20",
    "stalenessStatus": "active",
    "listingKind": "standalone",
    "firstImportedAt": "2026-08-15",
    "lastUpdatedAt": "2026-08-25",
    "compare": {
      "freeCore": false,
      "intermediary": false,
      "verification": "Open source project / maintainer (see platform terms)",
      "notes": "Source: OSS.Fund. Zero fees for first $10M donated through CommunityBridge. After that, 5% platform fee plus the payment processor’s fee."
    }
  },
  {
    "id": "ossfund-eventyay",
    "slug": "eventyay",
    "name": "eventyay",
    "category": "open_source",
    "offerType": "grant_credit",
    "resourceKind": "vendor_plan",
    "summary": "eventyay is an open source event management solution for virtual and onsite events. Imported from OSS.Fund on 2026-08-15 under CC BY 4.0.",
    "details": "eventyay is an open source event solution for virtual and in-person events.\n\nFees (OSS.Fund): Free for free events, 3% per paid ticket\n\nImported from OSS.Fund on 2026-08-15 under CC BY 4.0. Canonical listing: https://www.oss.fund/eventyay/",
    "absolutelyFree": false,
    "intermediaryRequired": false,
    "verification": [
      "none"
    ],
    "directPortalUrl": "https://eventyay.com",
    "metaResource": false,
    "tags": [
      "oss.fund",
      "oss-project",
      "events",
      "open-source-friendly",
      "marketplace"
    ],
    "iconHint": "eventyay",
    "lastVerifiedAt": "2021-01-19",
    "stalenessStatus": "active",
    "listingKind": "standalone",
    "firstImportedAt": "2026-08-15",
    "lastUpdatedAt": "2026-08-25",
    "compare": {
      "freeCore": false,
      "intermediary": false,
      "verification": "Open source project / maintainer (see platform terms)",
      "notes": "Source: OSS.Fund. Free for free events, 3% per paid ticket"
    }
  },
  {
    "id": "ossfund-faiross",
    "slug": "faiross",
    "name": "FairOSS",
    "category": "open_source",
    "offerType": "grant_credit",
    "resourceKind": "vendor_plan",
    "summary": "FairOSS is a public benefit corporation with a mission to sustain the production and maintenance of freely shareable intellectual property. Imported from OSS.Fund on 2026-08-15 under CC BY 4.0.",
    "details": "FairOSS is a public benefit corporation with a mission to sustain the production and maintenance of freely shareable intellectual property. Using a community first approach, FairOSS is assembling a coalition of open source producers, consumers, and business and technology partners towards building the Groundwater program, a framework for sustainability.  FairOSS arranges equity and revenue financing with organizations benefiting from open source and allows them a way to broadcast their social responsibility through the use of FairOSS trademarks.  Funds raised by these activities are used to fund open source projects.\n\nFairOSS also offers membership programs designed to bootstrap the company, expand board level decision making, and build the foundations for membership benefits. \n\n### Fee details\n- \"Charter memberships (monthly, annual, lifetime) ($10, $100, $2000)\"\n- \"Equity commitment (based on company stage, reliance of open source software, current contributions to open source)\"\n- \"Revenue share commitment (based on company stage, reliance of open source software, current contributions to open source)\"\n- \"Fixed price sponsorship commitment (based on company stage, reliance of open source software, current contributions to open source)\"\n\n### Current status\n- \"Actively fundraising for open source project dependencies and company funding\".\n- \"Strengthening community connections and partnerships to build the Groundwater program\".\n\n### Monetization\nFundraise equity/funding from organizations using open source to support their project dependencies in exchange for a 'fair-trade' trademark for open source. Charter membership dues for involvement in core company activities.\n\nFees (OSS.Fund): Charter memberships ($10 - $2000) and equity commitment options\n\nImported from OSS.Fund on 2026-08-15 under CC BY 4.0. Canonical listing: https://www.oss.fund/faiross/",
    "absolutelyFree": false,
    "intermediaryRequired": false,
    "verification": [
      "none"
    ],
    "directPortalUrl": "https://faiross.org/",
    "metaResource": false,
    "tags": [
      "oss.fund",
      "oss-project",
      "crowdfunding",
      "open-source-friendly",
      "membership",
      "social-impact",
      "trademark"
    ],
    "iconHint": "faiross",
    "lastVerifiedAt": "2020-10-11",
    "stalenessStatus": "active",
    "listingKind": "standalone",
    "firstImportedAt": "2026-08-15",
    "lastUpdatedAt": "2026-08-25",
    "compare": {
      "freeCore": false,
      "intermediary": false,
      "verification": "Open source project / maintainer (see platform terms)",
      "notes": "Source: OSS.Fund. Charter memberships ($10 - $2000) and equity commitment options"
    }
  },
  {
    "id": "ossfund-fund-request",
    "slug": "fund-request",
    "name": "Fund Request",
    "category": "open_source",
    "offerType": "grant_credit",
    "resourceKind": "vendor_plan",
    "summary": "A decentralised marketplace for requesting development bug fixes, security audits, etc to the Open Source developer community. Imported from OSS.Fund on 2026-08-15 under CC BY 4.0.",
    "details": "A decentralised marketplace for requesting development bugfixes, security audits, etc to the Open Source developer community.\n\nFees (OSS.Fund): ?\n\nImported from OSS.Fund on 2026-08-15 under CC BY 4.0. Canonical listing: https://www.oss.fund/fund-request/",
    "absolutelyFree": false,
    "intermediaryRequired": false,
    "verification": [
      "none"
    ],
    "directPortalUrl": "https://fundrequest.io/",
    "metaResource": false,
    "tags": [
      "oss.fund",
      "oss-project",
      "bounties",
      "decentralized",
      "open-source-friendly",
      "developer-friendly"
    ],
    "iconHint": "fund-request",
    "lastVerifiedAt": "2020-06-20",
    "stalenessStatus": "active",
    "listingKind": "standalone",
    "firstImportedAt": "2026-08-15",
    "lastUpdatedAt": "2026-08-25",
    "compare": {
      "freeCore": false,
      "intermediary": false,
      "verification": "Open source project / maintainer (see platform terms)",
      "notes": "Source: OSS.Fund. ?"
    }
  },
  {
    "id": "ossfund-gitcoin",
    "slug": "gitcoin",
    "name": "Gitcoin",
    "category": "open_source",
    "offerType": "grant_credit",
    "resourceKind": "vendor_plan",
    "summary": "Gitcoin is the easiest way to leverage the open source community to incentivize or monetize work. Imported from OSS.Fund on 2026-08-15 under CC BY 4.0.",
    "details": "Gitcoin is the easiest wayto leverage the open source community to incentivize or monetize work.\n\nFees (OSS.Fund): 0%\n\nImported from OSS.Fund on 2026-08-15 under CC BY 4.0. Canonical listing: https://www.oss.fund/gitcoin/",
    "absolutelyFree": true,
    "intermediaryRequired": false,
    "verification": [
      "none"
    ],
    "directPortalUrl": "https://gitcoin.co/",
    "metaResource": false,
    "tags": [
      "oss.fund",
      "oss-project",
      "bounties",
      "donations",
      "grants",
      "decentralized",
      "open-source-friendly",
      "developer-friendly"
    ],
    "iconHint": "gitcoin",
    "lastVerifiedAt": "2020-06-20",
    "stalenessStatus": "active",
    "listingKind": "standalone",
    "firstImportedAt": "2026-08-15",
    "lastUpdatedAt": "2026-08-25",
    "compare": {
      "freeCore": true,
      "intermediary": false,
      "verification": "Open source project / maintainer (see platform terms)",
      "notes": "Source: OSS.Fund. 0%"
    }
  },
  {
    "id": "ossfund-github-sponsors",
    "slug": "github-sponsors",
    "name": "GitHub Sponsors",
    "category": "open_source",
    "offerType": "grant_credit",
    "resourceKind": "vendor_plan",
    "summary": "Allows the developer community to financially support the people who design, build, and maintain the open source projects they depend on, directly on GitHub. Imported from OSS.Fund on 2026-08-15 under CC BY 4.0.",
    "details": "Allows the developer community to financially support the people who design, build, and maintain the open source projects they depend on, directly on GitHub.\n\nFees (OSS.Fund): No charge fees, and Github covers payment processing costs for the first year\n\nImported from OSS.Fund on 2026-08-15 under CC BY 4.0. Canonical listing: https://www.oss.fund/github-sponsors/",
    "absolutelyFree": true,
    "intermediaryRequired": false,
    "verification": [
      "none"
    ],
    "directPortalUrl": "https://github.com/sponsors",
    "metaResource": false,
    "tags": [
      "oss.fund",
      "oss-project",
      "donations",
      "open-source-friendly",
      "developer-friendly"
    ],
    "iconHint": "github-sponsors",
    "lastVerifiedAt": "2020-06-20",
    "stalenessStatus": "active",
    "listingKind": "standalone",
    "firstImportedAt": "2026-08-15",
    "lastUpdatedAt": "2026-08-25",
    "compare": {
      "freeCore": true,
      "intermediary": false,
      "verification": "Open source project / maintainer (see platform terms)",
      "notes": "Source: OSS.Fund. No charge fees, and Github covers payment processing costs for the first year"
    }
  },
  {
    "id": "ossfund-git-pay",
    "slug": "git-pay",
    "name": "Gitpay",
    "category": "open_source",
    "offerType": "grant_credit",
    "resourceKind": "vendor_plan",
    "summary": "An issue bounty platform for Git-powered projects with an integrated payment system. Imported from OSS.Fund on 2026-08-15 under CC BY 4.0.",
    "details": "An issue bounty platform for Git-powered projects with an integrated payment system.\n\nFees (OSS.Fund): 8% for open source projects, 18% for private projects, 30% for support\n\nImported from OSS.Fund on 2026-08-15 under CC BY 4.0. Canonical listing: https://www.oss.fund/git-pay/",
    "absolutelyFree": false,
    "intermediaryRequired": false,
    "verification": [
      "none"
    ],
    "directPortalUrl": "https://gitpay.me",
    "metaResource": false,
    "tags": [
      "oss.fund",
      "oss-project",
      "bounties",
      "open-source-friendly",
      "developer-friendly"
    ],
    "iconHint": "git-pay",
    "lastVerifiedAt": "2020-06-20",
    "stalenessStatus": "active",
    "listingKind": "standalone",
    "firstImportedAt": "2026-08-15",
    "lastUpdatedAt": "2026-08-25",
    "compare": {
      "freeCore": false,
      "intermediary": false,
      "verification": "Open source project / maintainer (see platform terms)",
      "notes": "Source: OSS.Fund. 8% for open source projects, 18% for private projects, 30% for support"
    }
  },
  {
    "id": "ossfund-summer-of-code",
    "slug": "summer-of-code",
    "name": "Google Summer of Code",
    "category": "open_source",
    "offerType": "grant_credit",
    "resourceKind": "vendor_plan",
    "summary": "Google Summer of Code connects student developers with open source projects to work on a 10 week programming project during their break from school. Imported from OSS.Fund on 2026-08-15 under CC BY 4.0.",
    "details": "Google Summer of Code connects student developers with open source projects to work on a 10 week programming project during their break from school.\n\nFees (OSS.Fund): $1500+ based on student's location\n\nImported from OSS.Fund on 2026-08-15 under CC BY 4.0. Canonical listing: https://www.oss.fund/summer-of-code/",
    "absolutelyFree": true,
    "intermediaryRequired": false,
    "verification": [
      "none"
    ],
    "directPortalUrl": "https://summerofcode.withgoogle.com/",
    "metaResource": false,
    "tags": [
      "oss.fund",
      "oss-project",
      "grants",
      "non-profit",
      "open-source-friendly",
      "developer-friendly",
      "students"
    ],
    "iconHint": "summer-of-code",
    "lastVerifiedAt": "2021-01-02",
    "stalenessStatus": "active",
    "listingKind": "standalone",
    "firstImportedAt": "2026-08-15",
    "lastUpdatedAt": "2026-08-25",
    "compare": {
      "freeCore": true,
      "intermediary": false,
      "verification": "Open source project / maintainer (see platform terms)",
      "notes": "Source: OSS.Fund. $1500+ based on student's location"
    }
  },
  {
    "id": "ossfund-goteo",
    "slug": "goteo",
    "name": "Goteo",
    "category": "open_source",
    "offerType": "grant_credit",
    "resourceKind": "vendor_plan",
    "summary": "A collective financing and distributed collaboration platform for projects for giving individual rewards, and generating collective returns. Imported from OSS.Fund on 2026-08-15 under CC BY 4.0.",
    "details": "A platform for crowdfunding or collective financing and distributed collaboration (services, infrastructures, microtasks) for projects which, apart from giving individual rewards, also generate a collective return through fomenting the commons, open code and/or free knowledge.\n\nFees (OSS.Fund): 4%\n\nImported from OSS.Fund on 2026-08-15 under CC BY 4.0. Canonical listing: https://www.oss.fund/goteo/",
    "absolutelyFree": false,
    "intermediaryRequired": false,
    "verification": [
      "none"
    ],
    "directPortalUrl": "https://goteo.org/",
    "metaResource": false,
    "tags": [
      "oss.fund",
      "oss-project",
      "crowdfunding",
      "open-source-friendly",
      "developer-friendly",
      "creative-works",
      "social-impact"
    ],
    "iconHint": "goteo",
    "lastVerifiedAt": "2020-06-20",
    "stalenessStatus": "active",
    "listingKind": "standalone",
    "firstImportedAt": "2026-08-15",
    "lastUpdatedAt": "2026-08-25",
    "compare": {
      "freeCore": false,
      "intermediary": false,
      "verification": "Open source project / maintainer (see platform terms)",
      "notes": "Source: OSS.Fund. 4%"
    }
  },
  {
    "id": "ossfund-houdini",
    "slug": "houdini",
    "name": "Houdini",
    "category": "open_source",
    "offerType": "grant_credit",
    "resourceKind": "diy_oss",
    "summary": "Houdini is an all-in-one, self-hosted, open source fundraising software developed in Ruby on Rails. Imported from OSS.Fund on 2026-08-15 under CC BY 4.0.",
    "details": "Houdini is an all-in-one fundraising platform developed in Ruby on Rails and licensed under AGPL/LGP.\n\nFees (OSS.Fund): 0\n\nImported from OSS.Fund on 2026-08-15 under CC BY 4.0. Canonical listing: https://www.oss.fund/houdini/",
    "absolutelyFree": true,
    "intermediaryRequired": false,
    "verification": [
      "none"
    ],
    "directPortalUrl": "https://houdiniproject.org/",
    "metaResource": false,
    "tags": [
      "oss.fund",
      "oss-project",
      "donations",
      "crowdfunding",
      "non-profit",
      "self-hosted"
    ],
    "iconHint": "houdini",
    "lastVerifiedAt": "2020-06-20",
    "stalenessStatus": "active",
    "listingKind": "standalone",
    "firstImportedAt": "2026-08-15",
    "lastUpdatedAt": "2026-08-25",
    "compare": {
      "freeCore": true,
      "intermediary": false,
      "verification": "Open source project / maintainer (see platform terms)",
      "notes": "Source: OSS.Fund. 0"
    }
  },
  {
    "id": "ossfund-issue-hunt",
    "slug": "issue-hunt",
    "name": "Issue Hunt",
    "category": "open_source",
    "offerType": "grant_credit",
    "resourceKind": "vendor_plan",
    "summary": "Allows open source project owners to fund Github issues and developers to hunt the issues. Imported from OSS.Fund on 2026-08-15 under CC BY 4.0.",
    "details": "Allows open source project owners to fund Github issues and developers to hunt the issues.\n\nFees (OSS.Fund): 10%\n\nImported from OSS.Fund on 2026-08-15 under CC BY 4.0. Canonical listing: https://www.oss.fund/issue-hunt/",
    "absolutelyFree": false,
    "intermediaryRequired": false,
    "verification": [
      "none"
    ],
    "directPortalUrl": "https://issuehunt.io/",
    "metaResource": false,
    "tags": [
      "oss.fund",
      "oss-project",
      "bounties",
      "open-source-friendly",
      "developer-friendly"
    ],
    "iconHint": "issue-hunt",
    "lastVerifiedAt": "2020-06-20",
    "stalenessStatus": "active",
    "listingKind": "standalone",
    "firstImportedAt": "2026-08-15",
    "lastUpdatedAt": "2026-08-25",
    "compare": {
      "freeCore": false,
      "intermediary": false,
      "verification": "Open source project / maintainer (see platform terms)",
      "notes": "Source: OSS.Fund. 10%"
    }
  },
  {
    "id": "ossfund-liberapay",
    "slug": "liberapay",
    "name": "Liberapay",
    "category": "open_source",
    "offerType": "grant_credit",
    "resourceKind": "vendor_plan",
    "summary": "Liberapay is a recurrent donations platform where people who benefit from free work support creators. Imported from OSS.Fund on 2026-08-15 under CC BY 4.0.",
    "details": "Liberapay is a recurrent donations platform where people who benefit from free work support creators.\n\nFees (OSS.Fund): The average is expected to be below 5% in all cases.\n\nImported from OSS.Fund on 2026-08-15 under CC BY 4.0. Canonical listing: https://www.oss.fund/liberapay/",
    "absolutelyFree": false,
    "intermediaryRequired": false,
    "verification": [
      "none"
    ],
    "directPortalUrl": "https://liberapay.com/",
    "metaResource": false,
    "tags": [
      "oss.fund",
      "oss-project",
      "donations",
      "non-profit",
      "open-source-friendly",
      "developer-friendly",
      "creative-works"
    ],
    "iconHint": "liberapay",
    "lastVerifiedAt": "2020-06-20",
    "stalenessStatus": "active",
    "listingKind": "standalone",
    "firstImportedAt": "2026-08-15",
    "lastUpdatedAt": "2026-08-25",
    "compare": {
      "freeCore": false,
      "intermediary": false,
      "verification": "Open source project / maintainer (see platform terms)",
      "notes": "Source: OSS.Fund. The average is expected to be below 5% in all cases."
    }
  },
  {
    "id": "ossfund-libreselery",
    "slug": "libreselery",
    "name": "LibreSelery",
    "category": "open_source",
    "offerType": "grant_credit",
    "resourceKind": "diy_oss",
    "summary": "Continuous and automated donation distribution to your project contributors and dependencies. Integrated into Github Actions Imported from OSS.Fund on 2026-08-15 under CC BY 4.0.",
    "details": "LibreSelery is a tool to distribute funding in free and open source projects. With a new funding model, it offers transparent, automated and adaptable compensation of contributors. The aim is to replace the middleman in donation distribution as far as possible with a free and transparent algorithm. Unlike most other donation systems LibreSelery only offers a decentralized tool and not a platform.\n\nFees (OSS.Fund): Coinbase fee for buying or selling cryptocurrency. Sending between coinbase wallets is for free.\n\nImported from OSS.Fund on 2026-08-15 under CC BY 4.0. Canonical listing: https://www.oss.fund/libreselery/",
    "absolutelyFree": false,
    "intermediaryRequired": false,
    "verification": [
      "none"
    ],
    "directPortalUrl": "https://github.com/protontypes/libreselery",
    "metaResource": false,
    "tags": [
      "oss.fund",
      "oss-project",
      "donations",
      "decentralized",
      "open-source-friendly",
      "developer-friendly",
      "non-profit",
      "self-hosted",
      "continuous-integration"
    ],
    "iconHint": "libreselery",
    "lastVerifiedAt": "2020-09-03",
    "stalenessStatus": "active",
    "listingKind": "standalone",
    "firstImportedAt": "2026-08-15",
    "lastUpdatedAt": "2026-08-25",
    "compare": {
      "freeCore": false,
      "intermediary": false,
      "verification": "Open source project / maintainer (see platform terms)",
      "notes": "Source: OSS.Fund. Coinbase fee for buying or selling cryptocurrency. Sending between coinbase wallets is for free."
    }
  },
  {
    "id": "ossfund-nl-net",
    "slug": "nl-net",
    "name": "NLnet",
    "category": "open_source",
    "offerType": "grant_credit",
    "resourceKind": "vendor_plan",
    "summary": "Financially supporting organizations and people that contribute to an open information society with ideas to fix the internet since 1997. Imported from OSS.Fund on 2026-08-15 under CC BY 4.0.",
    "details": "Financially supporting organizations and people that contribute to an open information society with ideas to fix the internet since 1997.\n\nFees (OSS.Fund): 0\n\nImported from OSS.Fund on 2026-08-15 under CC BY 4.0. Canonical listing: https://www.oss.fund/nl-net/",
    "absolutelyFree": true,
    "intermediaryRequired": false,
    "verification": [
      "none"
    ],
    "directPortalUrl": "https://nlnet.nl/",
    "metaResource": false,
    "tags": [
      "oss.fund",
      "oss-project",
      "grants",
      "non-profit",
      "open-source-friendly",
      "developer-friendly"
    ],
    "iconHint": "nl-net",
    "lastVerifiedAt": "2020-06-20",
    "stalenessStatus": "active",
    "listingKind": "standalone",
    "firstImportedAt": "2026-08-15",
    "lastUpdatedAt": "2026-08-25",
    "compare": {
      "freeCore": true,
      "intermediary": false,
      "verification": "Open source project / maintainer (see platform terms)",
      "notes": "Source: OSS.Fund. 0"
    }
  },
  {
    "id": "ossfund-numfocus",
    "slug": "numfocus",
    "name": "NumFOCUS",
    "category": "open_source",
    "offerType": "grant_credit",
    "resourceKind": "vendor_plan",
    "summary": "NumFOCUS provides funding and resources for open source scientific computing projects. Imported from OSS.Fund on 2026-08-15 under CC BY 4.0.",
    "details": "NumFOCUS aims to ensure that funding and resources are available to sustain projects in the scientific data stack through programs that provide support for open source scientific computing projects.\n\nFees (OSS.Fund): 0\n\nImported from OSS.Fund on 2026-08-15 under CC BY 4.0. Canonical listing: https://www.oss.fund/numfocus/",
    "absolutelyFree": true,
    "intermediaryRequired": false,
    "verification": [
      "none"
    ],
    "directPortalUrl": "https://numfocus.org/",
    "metaResource": false,
    "tags": [
      "oss.fund",
      "oss-project",
      "grants",
      "open-source-friendly",
      "developer-friendly",
      "non-profit"
    ],
    "iconHint": "numfocus",
    "lastVerifiedAt": "2020-11-22",
    "stalenessStatus": "active",
    "listingKind": "standalone",
    "firstImportedAt": "2026-08-15",
    "lastUpdatedAt": "2026-08-25",
    "compare": {
      "freeCore": true,
      "intermediary": false,
      "verification": "Open source project / maintainer (see platform terms)",
      "notes": "Source: OSS.Fund. 0"
    }
  },
  {
    "id": "ossfund-open-collective",
    "slug": "open-collective",
    "name": "Open Collective",
    "category": "open_source",
    "offerType": "grant_credit",
    "resourceKind": "vendor_plan",
    "summary": "Provides tools for collectives to receive money and mechanisms to spend their money in a transparent way. Imported from OSS.Fund on 2026-08-15 under CC BY 4.0.",
    "details": "Provides tools for collectives to receive money and mechanisms to spend their money in a transparent way.\n\nFees (OSS.Fund): Usually between 10%-15%\n\nImported from OSS.Fund on 2026-08-15 under CC BY 4.0. Canonical listing: https://www.oss.fund/open-collective/",
    "absolutelyFree": false,
    "intermediaryRequired": false,
    "verification": [
      "none"
    ],
    "directPortalUrl": "https://opencollective.com/",
    "metaResource": false,
    "tags": [
      "oss.fund",
      "oss-project",
      "donations",
      "open-source-friendly",
      "social-impact"
    ],
    "iconHint": "open-collective",
    "lastVerifiedAt": "2020-06-20",
    "stalenessStatus": "active",
    "listingKind": "standalone",
    "firstImportedAt": "2026-08-15",
    "lastUpdatedAt": "2026-08-25",
    "compare": {
      "freeCore": false,
      "intermediary": false,
      "verification": "Open source project / maintainer (see platform terms)",
      "notes": "Source: OSS.Fund. Usually between 10%-15%"
    }
  },
  {
    "id": "ossfund-open-source-design",
    "slug": "open-source-design",
    "name": "Open Source Design",
    "category": "open_source",
    "offerType": "grant_credit",
    "resourceKind": "vendor_plan",
    "summary": "A community of designers and developers pushing open design processes and improving design of open source software. Imported from OSS.Fund on 2026-08-15 under CC BY 4.0.",
    "details": "A community of designers and developers pushing open design processes and improving design of open source software.\n\nFees (OSS.Fund): 0\n\nImported from OSS.Fund on 2026-08-15 under CC BY 4.0. Canonical listing: https://www.oss.fund/open-source-design/",
    "absolutelyFree": true,
    "intermediaryRequired": false,
    "verification": [
      "none"
    ],
    "directPortalUrl": "https://opensourcedesign.net/",
    "metaResource": false,
    "tags": [
      "oss.fund",
      "oss-project",
      "bounties",
      "non-profit",
      "design"
    ],
    "iconHint": "open-source-design",
    "lastVerifiedAt": "2020-06-20",
    "stalenessStatus": "active",
    "listingKind": "standalone",
    "firstImportedAt": "2026-08-15",
    "lastUpdatedAt": "2026-08-25",
    "compare": {
      "freeCore": true,
      "intermediary": false,
      "verification": "Open source project / maintainer (see platform terms)",
      "notes": "Source: OSS.Fund. 0"
    }
  },
  {
    "id": "ossfund-osuosl",
    "slug": "osuosl",
    "name": "Open Source Lab",
    "category": "cloud_hosting",
    "offerType": "grant_credit",
    "resourceKind": "vendor_plan",
    "summary": "The Open Source Lab is a nonprofit organization working for the advancement of open source technologies by providing hosting to open source projects. Imported from OSS.Fund on 2026-08-15 under CC BY 4.0.",
    "details": "The Open Source Lab is a nonprofit organization working for the advancement of open source technologies by providing hosting to open source projects.\n\nFees (OSS.Fund): 0\n\nImported from OSS.Fund on 2026-08-15 under CC BY 4.0. Canonical listing: https://www.oss.fund/osuosl/",
    "absolutelyFree": true,
    "intermediaryRequired": false,
    "verification": [
      "none"
    ],
    "directPortalUrl": "https://osuosl.org/",
    "metaResource": false,
    "tags": [
      "oss.fund",
      "oss-project",
      "infrastructure",
      "open-source-friendly",
      "developer-friendly",
      "hosting"
    ],
    "iconHint": "osuosl",
    "lastVerifiedAt": "2021-01-02",
    "stalenessStatus": "active",
    "listingKind": "standalone",
    "firstImportedAt": "2026-08-15",
    "lastUpdatedAt": "2026-08-25",
    "compare": {
      "freeCore": true,
      "intermediary": false,
      "verification": "Open source project / maintainer (see platform terms)",
      "notes": "Source: OSS.Fund. 0"
    }
  },
  {
    "id": "ossfund-openssf",
    "slug": "openssf",
    "name": "Open Source Security Foundation",
    "category": "open_source",
    "offerType": "grant_credit",
    "resourceKind": "vendor_plan",
    "summary": "A Linux Foundation initiative to provide a forum for a collaborative, cross-industry effort for ensuring open source security. Imported from OSS.Fund on 2026-08-15 under CC BY 4.0.",
    "details": "A Linux Foundation initiative to provide a forum for a collaborative, cross-industry effort for ensuring open source security.\n\nFees (OSS.Fund): 0\n\nImported from OSS.Fund on 2026-08-15 under CC BY 4.0. Canonical listing: https://www.oss.fund/openssf/",
    "absolutelyFree": true,
    "intermediaryRequired": false,
    "verification": [
      "none"
    ],
    "directPortalUrl": "https://openssf.org/",
    "metaResource": false,
    "tags": [
      "oss.fund",
      "oss-project",
      "grants",
      "non-profit",
      "open-source-friendly",
      "security"
    ],
    "iconHint": "openssf",
    "lastVerifiedAt": "2021-01-02",
    "stalenessStatus": "active",
    "listingKind": "standalone",
    "firstImportedAt": "2026-08-15",
    "lastUpdatedAt": "2026-08-25",
    "compare": {
      "freeCore": true,
      "intermediary": false,
      "verification": "Open source project / maintainer (see platform terms)",
      "notes": "Source: OSS.Fund. 0"
    }
  },
  {
    "id": "ossfund-opire",
    "slug": "opire",
    "name": "Opire",
    "category": "open_source",
    "offerType": "grant_credit",
    "resourceKind": "vendor_plan",
    "summary": "Opire is a bounty platform where anyone can put bounties on any GitHub issue, which are only paid out once resolved. Imported from OSS.Fund on 2026-08-15 under CC BY 4.0.",
    "details": "Opire is a bounty platform where anyone can put bounties on any GitHub issue, which are only paid out once resolved. Contributors earn money by solving these challenges and claiming rewards. The platform promotes collaboration by allowing multiple bounties to be pooled together, and contributors can also receive tips for their efforts. With lower fees, Opire encourages more contributions and fosters an engaged community of problem-solvers.\n\nFees (OSS.Fund): 4% platform fee + Stripe processing fee, paid by bounty creators on top of bounty amount\n\nImported from OSS.Fund on 2026-08-15 under CC BY 4.0. Canonical listing: https://www.oss.fund/opire/",
    "absolutelyFree": false,
    "intermediaryRequired": false,
    "verification": [
      "none"
    ],
    "directPortalUrl": "https://opire.dev/",
    "metaResource": false,
    "tags": [
      "oss.fund",
      "oss-project",
      "bounties",
      "crowdfunding",
      "developer-friendly",
      "open-source-friendly",
      "marketplace"
    ],
    "iconHint": "opire",
    "lastVerifiedAt": "2024-09-22",
    "stalenessStatus": "active",
    "listingKind": "standalone",
    "firstImportedAt": "2026-08-15",
    "lastUpdatedAt": "2026-08-25",
    "compare": {
      "freeCore": false,
      "intermediary": false,
      "verification": "Open source project / maintainer (see platform terms)",
      "notes": "Source: OSS.Fund. 4% platform fee + Stripe processing fee, paid by bounty creators on top of bounty amount"
    }
  },
  {
    "id": "ossfund-season-of-docs",
    "slug": "season-of-docs",
    "name": "Season of Docs",
    "category": "open_source",
    "offerType": "grant_credit",
    "resourceKind": "vendor_plan",
    "summary": "A stipend program by Google that bring open source projects and technical writers together, to the benefit of both. Imported from OSS.Fund on 2026-08-15 under CC BY 4.0.",
    "details": "A stipend program by Google that bring open source projects and technical writers together, to the benefit of both.\n\nFees (OSS.Fund): $500 per paid to mentor, wheras writer's stipend is dependent on the location\n\nImported from OSS.Fund on 2026-08-15 under CC BY 4.0. Canonical listing: https://www.oss.fund/season-of-docs/",
    "absolutelyFree": true,
    "intermediaryRequired": false,
    "verification": [
      "none"
    ],
    "directPortalUrl": "https://developers.google.com/season-of-docs",
    "metaResource": false,
    "tags": [
      "oss.fund",
      "oss-project",
      "grants",
      "content",
      "non-profit",
      "open-source-friendly",
      "documentation"
    ],
    "iconHint": "season-of-docs",
    "lastVerifiedAt": "2021-01-02",
    "stalenessStatus": "active",
    "listingKind": "standalone",
    "firstImportedAt": "2026-08-15",
    "lastUpdatedAt": "2026-08-25",
    "compare": {
      "freeCore": true,
      "intermediary": false,
      "verification": "Open source project / maintainer (see platform terms)",
      "notes": "Source: OSS.Fund. $500 per paid to mentor, wheras writer's stipend is dependent on the location"
    }
  },
  {
    "id": "ossfund-sf-conservancy",
    "slug": "sf-conservancy",
    "name": "Software Freedom Conservancy",
    "category": "open_source",
    "offerType": "grant_credit",
    "resourceKind": "vendor_plan",
    "summary": "A not-for-profit charity that helps promote, improve, develop, and defend FLOSS projects. Imported from OSS.Fund on 2026-08-15 under CC BY 4.0.",
    "details": "A not-for-profit charity that helps promote, improve, develop, and defend FLOSS projects.\n\nFees (OSS.Fund): 10%\n\nImported from OSS.Fund on 2026-08-15 under CC BY 4.0. Canonical listing: https://www.oss.fund/sf-conservancy/",
    "absolutelyFree": false,
    "intermediaryRequired": false,
    "verification": [
      "none"
    ],
    "directPortalUrl": "https://sfconservancy.org/",
    "metaResource": false,
    "tags": [
      "oss.fund",
      "oss-project",
      "donations",
      "non-profit",
      "open-source-friendly",
      "developer-friendly"
    ],
    "iconHint": "sf-conservancy",
    "lastVerifiedAt": "2020-06-20",
    "stalenessStatus": "active",
    "listingKind": "standalone",
    "firstImportedAt": "2026-08-15",
    "lastUpdatedAt": "2026-08-25",
    "compare": {
      "freeCore": false,
      "intermediary": false,
      "verification": "Open source project / maintainer (see platform terms)",
      "notes": "Source: OSS.Fund. 10%"
    }
  },
  {
    "id": "ossfund-spi",
    "slug": "spi",
    "name": "Software in the Public Interest",
    "category": "open_source",
    "offerType": "grant_credit",
    "resourceKind": "vendor_plan",
    "summary": "A non-profit organization to help organizations develop and distribute open hardware and software. Imported from OSS.Fund on 2026-08-15 under CC BY 4.0.",
    "details": "A non-profit organization to help organizations develop and distribute open hardware and software.\n\nFees (OSS.Fund): 0\n\nImported from OSS.Fund on 2026-08-15 under CC BY 4.0. Canonical listing: https://www.oss.fund/spi/",
    "absolutelyFree": true,
    "intermediaryRequired": false,
    "verification": [
      "none"
    ],
    "directPortalUrl": "https://www.spi-inc.org/",
    "metaResource": false,
    "tags": [
      "oss.fund",
      "oss-project",
      "donations",
      "grants",
      "non-profit",
      "open-source-friendly",
      "developer-friendly",
      "legal"
    ],
    "iconHint": "spi",
    "lastVerifiedAt": "2020-06-20",
    "stalenessStatus": "active",
    "listingKind": "standalone",
    "firstImportedAt": "2026-08-15",
    "lastUpdatedAt": "2026-08-25",
    "compare": {
      "freeCore": true,
      "intermediary": false,
      "verification": "Open source project / maintainer (see platform terms)",
      "notes": "Source: OSS.Fund. 0"
    }
  },
  {
    "id": "ossfund-sovereign-tech-fund",
    "slug": "sovereign-tech-fund",
    "name": "Sovereign Tech Fund",
    "category": "open_source",
    "offerType": "grant_credit",
    "resourceKind": "vendor_plan",
    "summary": "The Sovereign Tech Fund supports the development, improvement and maintenance of open digital infrastructure. Imported from OSS.Fund on 2026-08-15 under CC BY 4.0.",
    "details": "The Sovereign Tech Fund supports the development, improvement and maintenance of open digital infrastructure. Our goal is to sustainably strengthen the open source ecosystem. We focus on security, resilience, technological diversity, and the people behind the code.\n\nFees (OSS.Fund): 0\n\nImported from OSS.Fund on 2026-08-15 under CC BY 4.0. Canonical listing: https://www.oss.fund/sovereign-tech-fund/",
    "absolutelyFree": true,
    "intermediaryRequired": false,
    "verification": [
      "none"
    ],
    "directPortalUrl": "https://sovereigntechfund.de/en/",
    "metaResource": false,
    "tags": [
      "oss.fund",
      "oss-project",
      "grants",
      "developer-friendly",
      "open-source-friendly"
    ],
    "iconHint": "sovereign-tech-fund",
    "lastVerifiedAt": "2023-06-01",
    "stalenessStatus": "active",
    "listingKind": "standalone",
    "firstImportedAt": "2026-08-15",
    "lastUpdatedAt": "2026-08-25",
    "compare": {
      "freeCore": true,
      "intermediary": false,
      "verification": "Open source project / maintainer (see platform terms)",
      "notes": "Source: OSS.Fund. 0"
    }
  },
  {
    "id": "ossfund-thanks",
    "slug": "thanks",
    "name": "Thanks",
    "category": "open_source",
    "offerType": "grant_credit",
    "resourceKind": "vendor_plan",
    "summary": "A tool that helps you see if any of the software you depend on has authors seeking for donations Imported from OSS.Fund on 2026-08-15 under CC BY 4.0.",
    "details": "A little tool you can use with npm (the package manager for Node.js) called thanks that helps you see if any of the software you depend on has authors who are seeking donations to continue their work.\n\nFees (OSS.Fund): 0\n\nImported from OSS.Fund on 2026-08-15 under CC BY 4.0. Canonical listing: https://www.oss.fund/thanks/",
    "absolutelyFree": true,
    "intermediaryRequired": false,
    "verification": [
      "none"
    ],
    "directPortalUrl": "https://github.com/feross/thanks",
    "metaResource": false,
    "tags": [
      "oss.fund",
      "oss-project",
      "donations",
      "developer-friendly",
      "open-source-friendly"
    ],
    "iconHint": "thanks",
    "lastVerifiedAt": "2020-06-20",
    "stalenessStatus": "active",
    "listingKind": "standalone",
    "firstImportedAt": "2026-08-15",
    "lastUpdatedAt": "2026-08-25",
    "compare": {
      "freeCore": true,
      "intermediary": false,
      "verification": "Open source project / maintainer (see platform terms)",
      "notes": "Source: OSS.Fund. 0"
    }
  },
  {
    "id": "ossfund-tidelift",
    "slug": "tidelift",
    "name": "Tidelift",
    "category": "open_source",
    "offerType": "diy_oss",
    "resourceKind": "vendor_plan",
    "summary": "Professional assurances directly from the open source experts who know it best. Imported from OSS.Fund on 2026-08-15 under CC BY 4.0.",
    "details": "Professional assurances directly from the open source experts who know it best.\n\nFees (OSS.Fund): $1500/month\n\nImported from OSS.Fund on 2026-08-15 under CC BY 4.0. Canonical listing: https://www.oss.fund/tidelift/",
    "absolutelyFree": false,
    "intermediaryRequired": false,
    "verification": [
      "none"
    ],
    "directPortalUrl": "https://tidelift.com/",
    "metaResource": false,
    "tags": [
      "oss.fund",
      "oss-project",
      "support",
      "open-source-friendly",
      "developer-friendly"
    ],
    "iconHint": "tidelift",
    "lastVerifiedAt": "2020-06-20",
    "stalenessStatus": "active",
    "listingKind": "standalone",
    "firstImportedAt": "2026-08-15",
    "lastUpdatedAt": "2026-08-25",
    "compare": {
      "freeCore": false,
      "intermediary": false,
      "verification": "Open source project / maintainer (see platform terms)",
      "notes": "Source: OSS.Fund. $1500/month"
    }
  }
];
